apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: academy-guidance
  namespace: academy-console-plugin
spec:
  output:
    to:
      kind: ImageStreamTag
      name: academy-guidance:0.1.0-ocp4.20
