apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "academy.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "academy.labels" . | nindent 4 }}
data:
  nginx.conf: |
    error_log /dev/stdout info;
    events {}
    http {
      access_log /dev/stdout;
      include /etc/nginx/mime.types;
      default_type application/octet-stream;
      server {
        listen 9443 ssl;
        ssl_certificate /var/cert/tls.crt;
        ssl_certificate_key /var/cert/tls.key;
        root /usr/share/nginx/html;
      }
    }
